extend type Booking {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Booking", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`renter`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  renterId: UUID! @fdc_generated(from: "Booking.renter", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`villa`. It must match the value of `Villa`.`id`. See `@ref` for how to customize it.
  """
  villaId: UUID! @fdc_generated(from: "Booking.villa", purpose: IMPLICIT_REF_FIELD)
}
extend type Review {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Review", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`reviewer`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  reviewerId: UUID! @fdc_generated(from: "Review.reviewer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`villa`. It must match the value of `Villa`.`id`. See `@ref` for how to customize it.
  """
  villaId: UUID! @fdc_generated(from: "Review.villa", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type Villa {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Villa", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Villa`.`owner`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  ownerId: UUID! @fdc_generated(from: "Villa.owner", purpose: IMPLICIT_REF_FIELD)
}
